[package]
name = "lff"
version = "0.1.0"
authors = ["bes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
shellexpand = "1.0.0"
rayon = "1.2.0"